### Numpy arrays from lists and tuples 

In [1]:
import numpy as np

In [2]:
Lis1 = [1,2,3,4,5]

#### Creating numpy array fro a list
- use np.array(lis_name)


In [3]:
np_lis1 = np.array(Lis1)

In [4]:
np_lis1

array([1, 2, 3, 4, 5])

-   If we use use mixed datatype, numpy will convert everything into common datatype say float, string

In [6]:
lis2 = [1,2, "abs"]

In [8]:
np_lis2 = np.array(lis2)
np_lis2

array(['1', '2', 'abs'], dtype='<U11')

#### From tuples

In [9]:
tup1 = ('1','2','abc')
# tuples are immutable lists

In [10]:
np_tup = np.array(tup1)
np_tup

array(['1', '2', 'abc'], dtype='<U3')

 #### Numpy array creation functions
 
 #### 1.  From arange function

In [12]:
np_org1 = np.arange(10)
np_org1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np_org2 = np.arange(100,150)
np_org2

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [14]:
np_org3 = np.arange(100,151,2)
np_org3

# 2 represents step size, by default the step size is 1.

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

#### Arrays using linspace
- It is used for creating floating numbers , that are equally placed
- Here the third parameter specifies the number of elements


In [16]:
 np_float = np.linspace(10,20,5) 
np_float

# Here we get five floating numbers between 10 and 20
# It is useful for creating distributions
# here the last number is inclusive whereas in arange it is not.

array([10. , 12.5, 15. , 17.5, 20. ])

#### Arrays using random.rand
- It creates random floats
- one argument , one dimentional arrays
- two args, two dimemtional with rows and columns

In [17]:
np_rand1 = np.random.rand(5)

In [18]:
np_rand1

array([0.02134945, 0.2405571 , 0.29367587, 0.99600645, 0.91807199])

In [19]:
np_rand2 = np.random.rand(5,3)

In [20]:
np_rand2
# here we 2-D array with 5 rows and 3 columns

array([[0.76713478, 0.86907828, 0.85244575],
       [0.31632024, 0.39507827, 0.27448394],
       [0.49488945, 0.76666347, 0.66799738],
       [0.99404063, 0.93334303, 0.80503453],
       [0.74997491, 0.19228916, 0.78503565]])

#### Arrays using random.randint
- It creates random integers between starting and ending points, 
- The third arg is the number of elements required

In [21]:
np_int = np.random.randint(0,100,5)

In [22]:
np_int
# here we five random integers between 0 and 100

array([86, 87, 74, 81, 31])

In [23]:
np_int2 = np.random.randint(20,4,6)
# here the starting pt has to be lower than ending pt or upper limit

ValueError: low >= high

#### Numpy zeros and ones
- Here for creating two dimensional we need to pass the numbers in a tuple

In [25]:
np_zeros = np.zeros(5)
np_zeros

array([0., 0., 0., 0., 0.])

In [26]:
np_zeros2 = np.zeros((2,4))
np_zeros2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
# Here we can also specify the data thype
np_ones = np.ones((2,3), dtype = int)
np_ones

array([[1, 1, 1],
       [1, 1, 1]])

#### np.fill(),np.full(),np.empty()
- empty() creates an empty array of the said datatype
- fill() fills the empty array with the given contant value
- fill() is for one dimensional constant arrays
- full() can create multi dimensional arrays, there is no need for empty array creation
    

In [28]:
np_empty = np.empty(5,dtype=int)
np_empty

array([1561773696,        487,          0,          0,          1])

In [29]:
np_empty.fill(13)

In [30]:
np_empty

array([13, 13, 13, 13, 13])

In [31]:
np_empty1 = np.empty(5,dtype='str')
np_empty1

array(['', '', '', '', ''], dtype='<U1')

In [32]:
np_empty1.fill('Love')

In [33]:
np_empty1
# it takes only the first letter

array(['L', 'L', 'L', 'L', 'L'], dtype='<U1')

In [34]:
# np.full()
np_full1 = np.full(5,42)
np_full1

# it creates an array with 5 elements and each equals 42

array([42, 42, 42, 42, 42])

In [35]:
np_full2d = np.full((2,5),16)
np_full2d

# you get 2D array with 2 rows and 5 columns

array([[16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16]])

#### Array insertion, deletion, and sorting

In [3]:
# np.insert(array_name,index position,value)

np_ins = np.array([1,2,3,5])
np_ins = np.insert(np_ins,3,4)  # you need to assign it to the variable
np_ins

# at the third index position you insert the element 4


array([1, 2, 3, 4, 5])

In [4]:
# np.append(array_name,value)
# always inserts at the end
np_ins = np.append(np_ins,6)
np_ins

array([1, 2, 3, 4, 5, 6])

In [5]:
#np.delete(array_name,index psition)
np_ins = np.delete(np_ins,5)
np_ins

array([1, 2, 3, 4, 5])

#### Copies and views
- Copies using .copy() changes address location
- direct assignment gives an another view of the same variable, changes made in one, reflects in another.
- id(array_name) gives the address location of the array

In [6]:
arr_1 = np.array([1,2,3,4])
arr_2 = arr_1

In [7]:
print(id(arr_1))
print(id(arr_2))
# both have same ids

2507837362416
2507837362416


In [12]:
arr_2[0] = 0

In [13]:
arr_1
# changes in one, reflects in the other

array([0, 2, 3, 4])

In [14]:
arr_2

array([0, 2, 3, 4])

In [16]:
arr_3 = arr_1.copy()
arr_3[0] = 1
arr_3
# here the arr_1 will not be affected

array([1, 2, 3, 4])

In [17]:
arr_1

array([0, 2, 3, 4])

In [18]:
# using .view() is similar to assignment operation, changes are reflected.

#### Array Reshape
- changes the dimension
- np.reshape(arr_name,(n,m)) or (n,m,o) depending on the dimension required
- np.reshape(arr_name, -1) flattens or convers any array to one dimensional array

In [19]:
np_res = np.array([[1,2],[3,4]])
np_res

array([[1, 2],
       [3, 4]])

In [20]:
np_flat = np.reshape(np_res,-1)
np_flat

array([1, 2, 3, 4])

In [21]:
# we have two more functions flatten and ravel for converting to one dimensions
#ravel is more memory efficient, but it can affect the original array.

In [22]:
np_res

array([[1, 2],
       [3, 4]])

In [23]:
np_res[-1,-1]
# gives last element of the array

4