In [1]:
import numpy as np

In [14]:
a = np.array([5,6,9])

In [3]:
# accessing elements via index positions
a[0]

5

In [5]:
# two dimensional
b = np.array([[4,5],[6,7],[9,0]])

In [6]:
# to fing the dimensions use ndim
b.ndim

2

In [7]:
# to know the byte size
a.itemsize

4

In [8]:
# to know datatype
a.dtype

dtype('int32')

In [9]:
# by default it is int, we can also give datatype as parameter
b = np.array([[4,5],[6,7],[9,0]], dtype= np.float64)

In [10]:
b.itemsize

8

In [11]:
# to know the no. of elements
b.size

6

In [12]:
# shape gives the row and columns
b.shape

(3, 2)

In [15]:
a.shape

(3,)

In [17]:
# array od zeroes and ones
azeroes = np.zeros((3,2))
aones = np.ones((3,2))

In [18]:
azeroes

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
# numpy range
np.arange(1,5)

array([1, 2, 3, 4])

In [20]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [21]:
np.linspace(1,10,5)
# This is linear sequencing, you create equally spaced nos. The number elements is specified by third parameter.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
b

array([[4., 5.],
       [6., 7.],
       [9., 0.]])

In [24]:
b.reshape(2,3)
# reshape is not same as transpose, here the rearrangement of elements happen orderwise


array([[4., 5., 6.],
       [7., 9., 0.]])

In [25]:
# to make the array one dimensional use ravel fn
b.ravel()

array([4., 5., 6., 7., 9., 0.])

In [38]:
f = b.flat

In [39]:
f

In [26]:
# we can have arithmetic functions like
#b.min() b.max b.sum()   etc.

In [27]:
b.sum(axis=0)
# addition along column

array([19., 12.])

In [28]:
b.sum(axis=1)
# addition along row

array([ 9., 13.,  9.])

In [29]:
# b.sqrt() is wrong
np.sqrt(b)


# similarly for std deviation np.std(b),  a.dot(b) gives matrix product

array([[2.        , 2.23606798],
       [2.44948974, 2.64575131],
       [3.        , 0.        ]])

In [30]:
c = np.array([[2,4,5],[1,6,0],[7,8,9]])

In [31]:
# Indexing
c[1,2]
# row 1,colun 2

0

In [32]:
#slicing
c[0:2,2]

# row 0 and 1, column 2

array([5, 0])

In [33]:
c[-1,0:2]
# last row, 0th and 1st col

array([7, 8])

In [34]:
c[:,1:3]
# all rows, cloumn 1 and 2

array([[4, 5],
       [6, 0],
       [8, 9]])

In [36]:
# to get each row seperately

for row in c:
    print(row)

[2 4 5]
[1 6 0]
[7 8 9]


In [40]:
for cell in c.flat:
    print(cell)

2
4
5
1
6
0
7
8
9


In [42]:
# vertical stacking
cs = np.arange(6). reshape(3,2)
bs = np.arange(6,12).reshape(3,2)

In [43]:
cs

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
bs

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [45]:
# vertical stacking
np.vstack((cs,bs))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [46]:
# horizontal stacking
np.hstack((cs,bs))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [47]:
np.arange(30).reshape(2,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [48]:
sp = np.arange(30).reshape(2,15)
# splitting
r = np.hsplit(sp,5)

# similarly we  have vsplit also

In [49]:
r

[array([[ 0,  1,  2],
        [15, 16, 17]]),
 array([[ 3,  4,  5],
        [18, 19, 20]]),
 array([[ 6,  7,  8],
        [21, 22, 23]]),
 array([[ 9, 10, 11],
        [24, 25, 26]]),
 array([[12, 13, 14],
        [27, 28, 29]])]

In [50]:
a = np.arange(12).reshape(3,4)

In [51]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
# boolean arrays
b= a > 4

In [53]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [54]:
b.dtype
# b is a boolean array

dtype('bool')

In [56]:
# to find the element that are > 4 (true condition in b)
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [57]:
# you can also replace these elements with another number
a[b] = 1
a

array([[0, 1, 2, 3],
       [4, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# for saving txt
# use np.savetxt("name.txt",x)
# y = np.loadtxt("name.txt")